import { CardSuit, CardValue, type Deck } from "$lib/types/cards";

export const ARONSON_STACK: Deck = {
  id: "aronson-stack",
  title: "Aronson Stack",
  author: "Simon Aronson",
  longTitle: "Aronson Stack Trainer - Master the Aronson Memdeck",
  shortDescription:
    "The Aronson Stack is a memorized deck arrangement created by Simon Aronson, designed for a wide range of powerful card magic effects.",
  longDescription:
    "Free Aronson Stack trainer by Simon Aronson. Practice positional recall, adjacent card identification, and cut calculations for the Aronson memdeck.",
  pageDescription:
    "The Aronson Stack was created by Simon Aronson and first published in his book 'A Stack to Remember' (1979). It is one of the most popular and versatile memorized deck stacks in card magic. The stack appears completely random while offering an extraordinary number of built-in properties: multiple poker and bridge deals, spelling effects, coincidences, and much more. Aronson has published numerous routines exploiting the stack's hidden mathematical relationships, making it a favourite among serious card magicians worldwide.",
  cards: [
    { suit: CardSuit.Spades, value: CardValue.Jack, position: 1 },
    { suit: CardSuit.Clubs, value: CardValue.King, position: 2 },
    { suit: CardSuit.Clubs, value: CardValue.Five, position: 3 },
    { suit: CardSuit.Hearts, value: CardValue.Two, position: 4 },
    { suit: CardSuit.Spades, value: CardValue.Nine, position: 5 },
    { suit: CardSuit.Spades, value: CardValue.Ace, position: 6 },
    { suit: CardSuit.Hearts, value: CardValue.Three, position: 7 },
    { suit: CardSuit.Clubs, value: CardValue.Six, position: 8 },
    { suit: CardSuit.Diamonds, value: CardValue.Eight, position: 9 },
    { suit: CardSuit.Clubs, value: CardValue.Ace, position: 10 },
    { suit: CardSuit.Spades, value: CardValue.Ten, position: 11 },
    { suit: CardSuit.Hearts, value: CardValue.Five, position: 12 },
    { suit: CardSuit.Diamonds, value: CardValue.Two, position: 13 },
    { suit: CardSuit.Diamonds, value: CardValue.King, position: 14 },
    { suit: CardSuit.Diamonds, value: CardValue.Seven, position: 15 },
    { suit: CardSuit.Clubs, value: CardValue.Eight, position: 16 },
    { suit: CardSuit.Spades, value: CardValue.Three, position: 17 },
    { suit: CardSuit.Diamonds, value: CardValue.Ace, position: 18 },
    { suit: CardSuit.Spades, value: CardValue.Seven, position: 19 },
    { suit: CardSuit.Spades, value: CardValue.Five, position: 20 },
    { suit: CardSuit.Diamonds, value: CardValue.Queen, position: 21 },
    { suit: CardSuit.Hearts, value: CardValue.Ace, position: 22 },
    { suit: CardSuit.Spades, value: CardValue.Eight, position: 23 },
    { suit: CardSuit.Diamonds, value: CardValue.Three, position: 24 },
    { suit: CardSuit.Hearts, value: CardValue.Seven, position: 25 },
    { suit: CardSuit.Hearts, value: CardValue.Queen, position: 26 },
    { suit: CardSuit.Diamonds, value: CardValue.Five, position: 27 },
    { suit: CardSuit.Clubs, value: CardValue.Seven, position: 28 },
    { suit: CardSuit.Hearts, value: CardValue.Four, position: 29 },
    { suit: CardSuit.Hearts, value: CardValue.King, position: 30 },
    { suit: CardSuit.Diamonds, value: CardValue.Four, position: 31 },
    { suit: CardSuit.Diamonds, value: CardValue.Ten, position: 32 },
    { suit: CardSuit.Clubs, value: CardValue.Jack, position: 33 },
    { suit: CardSuit.Hearts, value: CardValue.Jack, position: 34 },
    { suit: CardSuit.Clubs, value: CardValue.Ten, position: 35 },
    { suit: CardSuit.Diamonds, value: CardValue.Jack, position: 36 },
    { suit: CardSuit.Spades, value: CardValue.Four, position: 37 },
    { suit: CardSuit.Hearts, value: CardValue.Ten, position: 38 },
    { suit: CardSuit.Hearts, value: CardValue.Six, position: 39 },
    { suit: CardSuit.Clubs, value: CardValue.Three, position: 40 },
    { suit: CardSuit.Spades, value: CardValue.Two, position: 41 },
    { suit: CardSuit.Hearts, value: CardValue.Nine, position: 42 },
    { suit: CardSuit.Spades, value: CardValue.King, position: 43 },
    { suit: CardSuit.Spades, value: CardValue.Six, position: 44 },
    { suit: CardSuit.Clubs, value: CardValue.Four, position: 45 },
    { suit: CardSuit.Hearts, value: CardValue.Eight, position: 46 },
    { suit: CardSuit.Clubs, value: CardValue.Nine, position: 47 },
    { suit: CardSuit.Spades, value: CardValue.Queen, position: 48 },
    { suit: CardSuit.Diamonds, value: CardValue.Six, position: 49 },
    { suit: CardSuit.Clubs, value: CardValue.Queen, position: 50 },
    { suit: CardSuit.Clubs, value: CardValue.Two, position: 51 },
    { suit: CardSuit.Diamonds, value: CardValue.Nine, position: 52 },
  ],
};
