import { CardSuit, CardValue, type Deck } from "$lib/types/cards";

export const ARONSON_STACK: Deck = {
  id: "aronson-stack",
  title: "Aronson Stack",
  author: "Simon Aronson",
  shortDescription:
    "The Aronson Stack is a memorized deck arrangement created by Simon Aronson, designed for a wide range of powerful card magic effects.",
  longDescription:
    "The Aronson Stack was created by Simon Aronson and first published in his book 'A Stack to Remember' (1979). It is one of the most popular and versatile memorized deck stacks in card magic. The stack appears completely random while offering an extraordinary number of built-in properties: multiple poker and bridge deals, spelling effects, coincidences, and much more. Aronson has published numerous routines exploiting the stack's hidden mathematical relationships, making it a favourite among serious card magicians worldwide.",
  cards: [
    { suit: CardSuit.Spades, value: CardValue.Jack, position: 1 },
    { suit: CardSuit.Hearts, value: CardValue.Four, position: 2 },
    { suit: CardSuit.Spades, value: CardValue.Five, position: 3 },
    { suit: CardSuit.Clubs, value: CardValue.Jack, position: 4 },
    { suit: CardSuit.Clubs, value: CardValue.Four, position: 5 },
    { suit: CardSuit.Diamonds, value: CardValue.Four, position: 6 },
    { suit: CardSuit.Spades, value: CardValue.Three, position: 7 },
    { suit: CardSuit.Hearts, value: CardValue.Two, position: 8 },
    { suit: CardSuit.Hearts, value: CardValue.Ten, position: 9 },
    { suit: CardSuit.Diamonds, value: CardValue.Jack, position: 10 },
    { suit: CardSuit.Spades, value: CardValue.King, position: 11 },
    { suit: CardSuit.Diamonds, value: CardValue.Ace, position: 12 },
    { suit: CardSuit.Hearts, value: CardValue.Queen, position: 13 },
    { suit: CardSuit.Clubs, value: CardValue.Three, position: 14 },
    { suit: CardSuit.Clubs, value: CardValue.Five, position: 15 },
    { suit: CardSuit.Hearts, value: CardValue.Ace, position: 16 },
    { suit: CardSuit.Hearts, value: CardValue.Nine, position: 17 },
    { suit: CardSuit.Hearts, value: CardValue.Seven, position: 18 },
    { suit: CardSuit.Clubs, value: CardValue.Queen, position: 19 },
    { suit: CardSuit.Diamonds, value: CardValue.Eight, position: 20 },
    { suit: CardSuit.Spades, value: CardValue.Two, position: 21 },
    { suit: CardSuit.Hearts, value: CardValue.Eight, position: 22 },
    { suit: CardSuit.Diamonds, value: CardValue.King, position: 23 },
    { suit: CardSuit.Diamonds, value: CardValue.Queen, position: 24 },
    { suit: CardSuit.Hearts, value: CardValue.Five, position: 25 },
    { suit: CardSuit.Hearts, value: CardValue.King, position: 26 },
    { suit: CardSuit.Spades, value: CardValue.Eight, position: 27 },
    { suit: CardSuit.Spades, value: CardValue.Ace, position: 28 },
    { suit: CardSuit.Hearts, value: CardValue.Six, position: 29 },
    { suit: CardSuit.Spades, value: CardValue.Ten, position: 30 },
    { suit: CardSuit.Spades, value: CardValue.Nine, position: 31 },
    { suit: CardSuit.Clubs, value: CardValue.King, position: 32 },
    { suit: CardSuit.Diamonds, value: CardValue.Ten, position: 33 },
    { suit: CardSuit.Diamonds, value: CardValue.Five, position: 34 },
    { suit: CardSuit.Diamonds, value: CardValue.Seven, position: 35 },
    { suit: CardSuit.Spades, value: CardValue.Queen, position: 36 },
    { suit: CardSuit.Hearts, value: CardValue.Jack, position: 37 },
    { suit: CardSuit.Spades, value: CardValue.Seven, position: 38 },
    { suit: CardSuit.Diamonds, value: CardValue.Two, position: 39 },
    { suit: CardSuit.Clubs, value: CardValue.Seven, position: 40 },
    { suit: CardSuit.Diamonds, value: CardValue.Six, position: 41 },
    { suit: CardSuit.Diamonds, value: CardValue.Nine, position: 42 },
    { suit: CardSuit.Hearts, value: CardValue.Three, position: 43 },
    { suit: CardSuit.Clubs, value: CardValue.Two, position: 44 },
    { suit: CardSuit.Clubs, value: CardValue.Ace, position: 45 },
    { suit: CardSuit.Diamonds, value: CardValue.Three, position: 46 },
    { suit: CardSuit.Clubs, value: CardValue.Eight, position: 47 },
    { suit: CardSuit.Clubs, value: CardValue.Ten, position: 48 },
    { suit: CardSuit.Spades, value: CardValue.Six, position: 49 },
    { suit: CardSuit.Clubs, value: CardValue.Nine, position: 50 },
    { suit: CardSuit.Clubs, value: CardValue.Six, position: 51 },
    { suit: CardSuit.Spades, value: CardValue.Four, position: 52 },
  ],
};
