import { CardSuit, CardValue, type Deck } from "$lib/types/cards";

export const MEMORANDUM: Deck = {
  id: "memorandum",
  title: "Memorandum",
  author: "Woody Aragon",
  shortDescription:
    "The Memorandum stack, created by Woody Aragon, is a memorized deck arrangement published in his book 'Memorandum'.",
  longDescription:
    "The Memorandum stack was created by Spanish magician Woody Aragon and published in his book 'Memorandum'. It is a carefully designed memorized deck stack that allows magicians to perform a wide variety of powerful card effects. Like other memorized deck systems, the stack appears random while containing hidden mathematical and structural properties that enable a broad range of routines.",
  cards: [
    { suit: CardSuit.Spades, value: CardValue.Jack, position: 1 },
    { suit: CardSuit.Clubs, value: CardValue.Seven, position: 2 },
    { suit: CardSuit.Hearts, value: CardValue.Ten, position: 3 },
    { suit: CardSuit.Diamonds, value: CardValue.Ace, position: 4 },
    { suit: CardSuit.Clubs, value: CardValue.Four, position: 5 },
    { suit: CardSuit.Hearts, value: CardValue.Seven, position: 6 },
    { suit: CardSuit.Diamonds, value: CardValue.Four, position: 7 },
    { suit: CardSuit.Spades, value: CardValue.Ace, position: 8 },
    { suit: CardSuit.Hearts, value: CardValue.Four, position: 9 },
    { suit: CardSuit.Diamonds, value: CardValue.Seven, position: 10 },
    { suit: CardSuit.Spades, value: CardValue.Four, position: 11 },
    { suit: CardSuit.Hearts, value: CardValue.Ace, position: 12 },
    { suit: CardSuit.Diamonds, value: CardValue.Ten, position: 13 },
    { suit: CardSuit.Spades, value: CardValue.Seven, position: 14 },
    { suit: CardSuit.Clubs, value: CardValue.Jack, position: 15 },
    { suit: CardSuit.Diamonds, value: CardValue.King, position: 16 },
    { suit: CardSuit.Spades, value: CardValue.Ten, position: 17 },
    { suit: CardSuit.Clubs, value: CardValue.Eight, position: 18 },
    { suit: CardSuit.Hearts, value: CardValue.Jack, position: 19 },
    { suit: CardSuit.Clubs, value: CardValue.Ace, position: 20 },
    { suit: CardSuit.Spades, value: CardValue.King, position: 21 },
    { suit: CardSuit.Clubs, value: CardValue.Five, position: 22 },
    { suit: CardSuit.Hearts, value: CardValue.Eight, position: 23 },
    { suit: CardSuit.Diamonds, value: CardValue.Three, position: 24 },
    { suit: CardSuit.Spades, value: CardValue.Queen, position: 25 },
    { suit: CardSuit.Hearts, value: CardValue.King, position: 26 },
    { suit: CardSuit.Clubs, value: CardValue.Nine, position: 27 },
    { suit: CardSuit.Hearts, value: CardValue.Queen, position: 28 },
    { suit: CardSuit.Clubs, value: CardValue.Six, position: 29 },
    { suit: CardSuit.Hearts, value: CardValue.Nine, position: 30 },
    { suit: CardSuit.Diamonds, value: CardValue.Two, position: 31 },
    { suit: CardSuit.Clubs, value: CardValue.Three, position: 32 },
    { suit: CardSuit.Hearts, value: CardValue.Six, position: 33 },
    { suit: CardSuit.Diamonds, value: CardValue.Five, position: 34 },
    { suit: CardSuit.Spades, value: CardValue.Two, position: 35 },
    { suit: CardSuit.Hearts, value: CardValue.Three, position: 36 },
    { suit: CardSuit.Diamonds, value: CardValue.Eight, position: 37 },
    { suit: CardSuit.Spades, value: CardValue.Five, position: 38 },
    { suit: CardSuit.Clubs, value: CardValue.King, position: 39 },
    { suit: CardSuit.Diamonds, value: CardValue.Jack, position: 40 },
    { suit: CardSuit.Spades, value: CardValue.Eight, position: 41 },
    { suit: CardSuit.Clubs, value: CardValue.Ten, position: 42 },
    { suit: CardSuit.Clubs, value: CardValue.Two, position: 43 },
    { suit: CardSuit.Hearts, value: CardValue.Five, position: 44 },
    { suit: CardSuit.Diamonds, value: CardValue.Six, position: 45 },
    { suit: CardSuit.Spades, value: CardValue.Three, position: 46 },
    { suit: CardSuit.Hearts, value: CardValue.Two, position: 47 },
    { suit: CardSuit.Diamonds, value: CardValue.Nine, position: 48 },
    { suit: CardSuit.Spades, value: CardValue.Six, position: 49 },
    { suit: CardSuit.Clubs, value: CardValue.Queen, position: 50 },
    { suit: CardSuit.Diamonds, value: CardValue.Queen, position: 51 },
    { suit: CardSuit.Spades, value: CardValue.Nine, position: 52 },
  ],
};
