import { CardSuit, CardValue, type Deck } from "$lib/types/cards";

export const MNEMONICA: Deck = {
  id: "mnemonica",
  title: "Mnemonica",
  author: "Juan Tamariz",
  shortDescription:
    "The Mnemonica stack, as described by Juan Tamariz in his book 'Mnemonica: The Art of Memory for Magicians'.",
  longDescription:
    "The Mnemonica stack, as described by Juan Tamariz in his book 'Mnemonica: The Art of Memory for Magicians'. It is a specific arrangement of a standard deck of 52 playing cards that is designed to allow magicians to perform a wide variety of card tricks and routines with ease. The stack is arranged in a way that allows for easy memorization and quick access to any card in the deck, making it a powerful tool for card magic.",
  cards: [
    { suit: CardSuit.Clubs, value: CardValue.Four, position: 1 },
    { suit: CardSuit.Hearts, value: CardValue.Two, position: 2 },
    { suit: CardSuit.Diamonds, value: CardValue.Seven, position: 3 },
    { suit: CardSuit.Clubs, value: CardValue.Three, position: 4 },
    { suit: CardSuit.Hearts, value: CardValue.Four, position: 5 },
    { suit: CardSuit.Diamonds, value: CardValue.Six, position: 6 },
    { suit: CardSuit.Spades, value: CardValue.Ace, position: 7 },
    { suit: CardSuit.Hearts, value: CardValue.Five, position: 8 },
    { suit: CardSuit.Spades, value: CardValue.Nine, position: 9 },
    { suit: CardSuit.Spades, value: CardValue.Two, position: 10 },
    { suit: CardSuit.Hearts, value: CardValue.Queen, position: 11 },
    { suit: CardSuit.Diamonds, value: CardValue.Three, position: 12 },
    { suit: CardSuit.Clubs, value: CardValue.Queen, position: 13 },
    { suit: CardSuit.Hearts, value: CardValue.Eight, position: 14 },
    { suit: CardSuit.Spades, value: CardValue.Six, position: 15 },
    { suit: CardSuit.Spades, value: CardValue.Five, position: 16 },
    { suit: CardSuit.Hearts, value: CardValue.Nine, position: 17 },
    { suit: CardSuit.Clubs, value: CardValue.King, position: 18 },
    { suit: CardSuit.Diamonds, value: CardValue.Two, position: 19 },
    { suit: CardSuit.Hearts, value: CardValue.Jack, position: 20 },
    { suit: CardSuit.Spades, value: CardValue.Three, position: 21 },
    { suit: CardSuit.Spades, value: CardValue.Eight, position: 22 },
    { suit: CardSuit.Hearts, value: CardValue.Six, position: 23 },
    { suit: CardSuit.Clubs, value: CardValue.Ten, position: 24 },
    { suit: CardSuit.Diamonds, value: CardValue.Five, position: 25 },
    { suit: CardSuit.Diamonds, value: CardValue.King, position: 26 },
    { suit: CardSuit.Clubs, value: CardValue.Two, position: 27 },
    { suit: CardSuit.Hearts, value: CardValue.Three, position: 28 },
    { suit: CardSuit.Diamonds, value: CardValue.Eight, position: 29 },
    { suit: CardSuit.Clubs, value: CardValue.Five, position: 30 },
    { suit: CardSuit.Spades, value: CardValue.King, position: 31 },
    { suit: CardSuit.Diamonds, value: CardValue.Jack, position: 32 },
    { suit: CardSuit.Clubs, value: CardValue.Eight, position: 33 },
    { suit: CardSuit.Spades, value: CardValue.Ten, position: 34 },
    { suit: CardSuit.Hearts, value: CardValue.King, position: 35 },
    { suit: CardSuit.Clubs, value: CardValue.Jack, position: 36 },
    { suit: CardSuit.Spades, value: CardValue.Seven, position: 37 },
    { suit: CardSuit.Hearts, value: CardValue.Ten, position: 38 },
    { suit: CardSuit.Diamonds, value: CardValue.Ace, position: 39 },
    { suit: CardSuit.Spades, value: CardValue.Four, position: 40 },
    { suit: CardSuit.Hearts, value: CardValue.Seven, position: 41 },
    { suit: CardSuit.Diamonds, value: CardValue.Four, position: 42 },
    { suit: CardSuit.Clubs, value: CardValue.Ace, position: 43 },
    { suit: CardSuit.Clubs, value: CardValue.Nine, position: 44 },
    { suit: CardSuit.Spades, value: CardValue.Jack, position: 45 },
    { suit: CardSuit.Diamonds, value: CardValue.Queen, position: 46 },
    { suit: CardSuit.Clubs, value: CardValue.Seven, position: 47 },
    { suit: CardSuit.Spades, value: CardValue.Queen, position: 48 },
    { suit: CardSuit.Diamonds, value: CardValue.Ten, position: 49 },
    { suit: CardSuit.Clubs, value: CardValue.Six, position: 50 },
    { suit: CardSuit.Hearts, value: CardValue.Ace, position: 51 },
    { suit: CardSuit.Diamonds, value: CardValue.Nine, position: 52 },
  ],
};
