import { CardSuit, CardValue, type Deck } from "$lib/types/cards";

export const REDFORD_STACK: Deck = {
  id: "redford-stack",
  title: "Redford Stack",
  author: "Patrick G. Redford",
  longTitle: "Redford Stack Trainer - Practice the Redford Memdeck",
  shortDescription:
    "The Redford Stack is a versatile memorized deck arrangement created by Patrick G. Redford, designed for powerful and flexible card magic effects.",
  longDescription:
    "Free Redford Stack trainer by Patrick G. Redford. Practice positional recall, adjacent card identification, and cut calculations for the Redford memdeck.",
  pageDescription:
    "The Redford Stack is a specially designed memorized deck system developed by Patrick G. Redford, known for its adaptability and wide range of applications in card magic. Unlike some traditional stacks, the Redford Stack can be set up quickly from a shuffled deck or a new pack of cards and even transitions into other stacked arrangements (like Si-Stebbins or mirror stacks) with ease. Packed with built-in features for spelling effects, poker and blackjack deals, coincidences, and faro routines, this stack appears random but offers a powerful toolset for performing deceptive and impressive card effects. Many routines with the stack can be performed without fully memorizing the order, making it accessible while still highly sophisticated.",
  cards: [
    { suit: CardSuit.Hearts, value: CardValue.Queen, position: 1 },
    { suit: CardSuit.Spades, value: CardValue.Two, position: 2 },
    { suit: CardSuit.Diamonds, value: CardValue.Five, position: 3 },
    { suit: CardSuit.Clubs, value: CardValue.Eight, position: 4 },
    { suit: CardSuit.Hearts, value: CardValue.Jack, position: 5 },
    { suit: CardSuit.Spades, value: CardValue.King, position: 6 },
    { suit: CardSuit.Hearts, value: CardValue.Ten, position: 7 },
    { suit: CardSuit.Clubs, value: CardValue.Seven, position: 8 },
    { suit: CardSuit.Diamonds, value: CardValue.Four, position: 9 },
    { suit: CardSuit.Spades, value: CardValue.Ace, position: 10 },
    { suit: CardSuit.Hearts, value: CardValue.Eight, position: 11 },
    { suit: CardSuit.Clubs, value: CardValue.Five, position: 12 },
    { suit: CardSuit.Diamonds, value: CardValue.Two, position: 13 },
    { suit: CardSuit.Spades, value: CardValue.Queen, position: 14 },
    { suit: CardSuit.Hearts, value: CardValue.Nine, position: 15 },
    { suit: CardSuit.Clubs, value: CardValue.Six, position: 16 },
    { suit: CardSuit.Diamonds, value: CardValue.Three, position: 17 },
    { suit: CardSuit.Spades, value: CardValue.Ten, position: 18 },
    { suit: CardSuit.Hearts, value: CardValue.Seven, position: 19 },
    { suit: CardSuit.Clubs, value: CardValue.Four, position: 20 },
    { suit: CardSuit.Diamonds, value: CardValue.Ace, position: 21 },
    { suit: CardSuit.Spades, value: CardValue.Jack, position: 22 },
    { suit: CardSuit.Spades, value: CardValue.Nine, position: 23 },
    { suit: CardSuit.Hearts, value: CardValue.Six, position: 24 },
    { suit: CardSuit.Clubs, value: CardValue.Three, position: 25 },
    { suit: CardSuit.Diamonds, value: CardValue.King, position: 26 },
    { suit: CardSuit.Diamonds, value: CardValue.Queen, position: 27 },
    { suit: CardSuit.Diamonds, value: CardValue.Ten, position: 28 },
    { suit: CardSuit.Spades, value: CardValue.Seven, position: 29 },
    { suit: CardSuit.Hearts, value: CardValue.Four, position: 30 },
    { suit: CardSuit.Clubs, value: CardValue.Ace, position: 31 },
    { suit: CardSuit.Diamonds, value: CardValue.Jack, position: 32 },
    { suit: CardSuit.Spades, value: CardValue.Eight, position: 33 },
    { suit: CardSuit.Hearts, value: CardValue.Five, position: 34 },
    { suit: CardSuit.Clubs, value: CardValue.Two, position: 35 },
    { suit: CardSuit.Hearts, value: CardValue.Two, position: 36 },
    { suit: CardSuit.Clubs, value: CardValue.Queen, position: 37 },
    { suit: CardSuit.Diamonds, value: CardValue.Nine, position: 38 },
    { suit: CardSuit.Spades, value: CardValue.Six, position: 39 },
    { suit: CardSuit.Hearts, value: CardValue.Three, position: 40 },
    { suit: CardSuit.Clubs, value: CardValue.King, position: 41 },
    { suit: CardSuit.Diamonds, value: CardValue.Four, position: 42 },
    { suit: CardSuit.Hearts, value: CardValue.Ace, position: 43 },
    { suit: CardSuit.Clubs, value: CardValue.Jack, position: 44 },
    { suit: CardSuit.Diamonds, value: CardValue.Eight, position: 45 },
    { suit: CardSuit.Spades, value: CardValue.Five, position: 46 },
    { suit: CardSuit.Spades, value: CardValue.Three, position: 47 },
    { suit: CardSuit.Hearts, value: CardValue.King, position: 48 },
    { suit: CardSuit.Clubs, value: CardValue.Ten, position: 49 },
    { suit: CardSuit.Diamonds, value: CardValue.Seven, position: 50 },
    { suit: CardSuit.Diamonds, value: CardValue.Six, position: 51 },
    { suit: CardSuit.Clubs, value: CardValue.Nine, position: 52 },
  ],
};
