import { CardSuit, CardValue, type Deck } from "$lib/types/cards";

// Si Stebbins stack: suits cycle CHaSeD (Clubs → Hearts → Spades → Diamonds),
// values increase by 3 each step (mod 13), starting with Ace of Clubs.
export const SI_STEBBINS: Deck = {
  id: "si-stebbins",
  title: "Si Stebbins",
  author: "Si Stebbins",
  shortDescription:
    "A mathematical stack where suits cycle CHaSeD and each card's value is 3 higher than the previous, allowing instant calculation of any card's position.",
  longDescription:
    "The Si Stebbins stack is one of the oldest and most elegant mathematical card stacks in magic. The system is simple: suits cycle in the order Clubs → Hearts → Spades → Diamonds (CHaSeD), and each successive card's value is exactly 3 higher than the previous (wrapping from King back to Ace). Starting with the Ace of Clubs, any card's position—or the card at any position—can be calculated instantly in your head without memorization. While the pattern is learnable by an astute observer, it remains a powerful tool for impromptu card magic and a gateway stack for magicians learning stacked decks.",
  cards: [
    { suit: CardSuit.Clubs, value: CardValue.Ace, position: 1 },
    { suit: CardSuit.Hearts, value: CardValue.Four, position: 2 },
    { suit: CardSuit.Spades, value: CardValue.Seven, position: 3 },
    { suit: CardSuit.Diamonds, value: CardValue.Ten, position: 4 },
    { suit: CardSuit.Clubs, value: CardValue.King, position: 5 },
    { suit: CardSuit.Hearts, value: CardValue.Three, position: 6 },
    { suit: CardSuit.Spades, value: CardValue.Six, position: 7 },
    { suit: CardSuit.Diamonds, value: CardValue.Nine, position: 8 },
    { suit: CardSuit.Clubs, value: CardValue.Queen, position: 9 },
    { suit: CardSuit.Hearts, value: CardValue.Two, position: 10 },
    { suit: CardSuit.Spades, value: CardValue.Five, position: 11 },
    { suit: CardSuit.Diamonds, value: CardValue.Eight, position: 12 },
    { suit: CardSuit.Clubs, value: CardValue.Jack, position: 13 },
    { suit: CardSuit.Hearts, value: CardValue.Ace, position: 14 },
    { suit: CardSuit.Spades, value: CardValue.Four, position: 15 },
    { suit: CardSuit.Diamonds, value: CardValue.Seven, position: 16 },
    { suit: CardSuit.Clubs, value: CardValue.Ten, position: 17 },
    { suit: CardSuit.Hearts, value: CardValue.King, position: 18 },
    { suit: CardSuit.Spades, value: CardValue.Three, position: 19 },
    { suit: CardSuit.Diamonds, value: CardValue.Six, position: 20 },
    { suit: CardSuit.Clubs, value: CardValue.Nine, position: 21 },
    { suit: CardSuit.Hearts, value: CardValue.Queen, position: 22 },
    { suit: CardSuit.Spades, value: CardValue.Two, position: 23 },
    { suit: CardSuit.Diamonds, value: CardValue.Five, position: 24 },
    { suit: CardSuit.Clubs, value: CardValue.Eight, position: 25 },
    { suit: CardSuit.Hearts, value: CardValue.Jack, position: 26 },
    { suit: CardSuit.Spades, value: CardValue.Ace, position: 27 },
    { suit: CardSuit.Diamonds, value: CardValue.Four, position: 28 },
    { suit: CardSuit.Clubs, value: CardValue.Seven, position: 29 },
    { suit: CardSuit.Hearts, value: CardValue.Ten, position: 30 },
    { suit: CardSuit.Spades, value: CardValue.King, position: 31 },
    { suit: CardSuit.Diamonds, value: CardValue.Three, position: 32 },
    { suit: CardSuit.Clubs, value: CardValue.Six, position: 33 },
    { suit: CardSuit.Hearts, value: CardValue.Nine, position: 34 },
    { suit: CardSuit.Spades, value: CardValue.Queen, position: 35 },
    { suit: CardSuit.Diamonds, value: CardValue.Two, position: 36 },
    { suit: CardSuit.Clubs, value: CardValue.Five, position: 37 },
    { suit: CardSuit.Hearts, value: CardValue.Eight, position: 38 },
    { suit: CardSuit.Spades, value: CardValue.Jack, position: 39 },
    { suit: CardSuit.Diamonds, value: CardValue.Ace, position: 40 },
    { suit: CardSuit.Clubs, value: CardValue.Four, position: 41 },
    { suit: CardSuit.Hearts, value: CardValue.Seven, position: 42 },
    { suit: CardSuit.Spades, value: CardValue.Ten, position: 43 },
    { suit: CardSuit.Diamonds, value: CardValue.King, position: 44 },
    { suit: CardSuit.Clubs, value: CardValue.Three, position: 45 },
    { suit: CardSuit.Hearts, value: CardValue.Six, position: 46 },
    { suit: CardSuit.Spades, value: CardValue.Nine, position: 47 },
    { suit: CardSuit.Diamonds, value: CardValue.Queen, position: 48 },
    { suit: CardSuit.Clubs, value: CardValue.Two, position: 49 },
    { suit: CardSuit.Hearts, value: CardValue.Five, position: 50 },
    { suit: CardSuit.Spades, value: CardValue.Eight, position: 51 },
    { suit: CardSuit.Diamonds, value: CardValue.Jack, position: 52 },
  ],
};
